import type { Metadata } from "next";
import { Averia_Serif_Libre, Kameron, Sanchez } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";

const kameron = Kameron({
  variable: "--font-kameron",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const averiaSerifLibre = Averia_Serif_Libre({
  variable: "--font-averia",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const sanchez = Sanchez({
  variable: "--font-sanchez",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../components/ThemeContext";
import SmoothScroller from "../components/SmoothScroller";
import LanguageTransitionProvider from "../components/LanguageTransition";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${kameron.variable} ${averiaSerifLibre.variable} ${sanchez.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            <LanguageTransitionProvider>
              <SmoothScroller />
              {children}
            </LanguageTransitionProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
